version: '3.1'
services:
  proxy-gateway:
    build: ../proxy-gateway
    ports:
      - '8080:80'
    depends_on:
      - event-publisher
      - entity-inspector
      - schema-inspector
      - schema-editor
  event-publisher:
    build: ../event-publisher
    ports:
      - '8001:50051'
    depends_on:
      - schema-inspector
      - event-store
  process-executor:
    build: ../process-executor
    ports:
      - '8002:50051'
    depends_on:
      - schema-inspector
  entity-inspector:
    build: ../entity-inspector
    ports:
      - '8003:50051'
    depends_on:
      - schema-inspector
      - data-store
  entity-editor:
    build: ../entity-editor
    ports:
      - '8004:50051'
  event-handler:
    build: ../event-handler
    depends_on:
      - process-executor
      - event-publisher
      - event-store
      - data-store
  schema-editor:
    build: ../schema-editor
    ports:
      - '8010:50051'
    environment:
      STORE_HOST: schema-store
      STORE_PORT: 7687
      STORE_USER: neo4j
      STORE_PASS: test
    depends_on:
      - schema-store
  schema-inspector:
    build: ../schema-inspector
    ports:
      - '8020:50051'
    environment:
      STORE_HOST: schema-store
      STORE_PORT: 7687
      STORE_USER: neo4j
      STORE_PASS: test
    depends_on:
      - schema-store
  schema-store:
    image: neo4j:3.5
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/test
  data-store:
    image: neo4j:3.5
    ports:
      - '7475:7474'
      - '7688:7687'
    environment:
      NEO4J_AUTH: neo4j/test
  event-viewer:
    image: 'obsidiandynamics/kafdrop'
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: "event-store:9092"
    depends_on:
      - event-store
  event-store:
    image: confluentinc/cp-kafka:5.4.0
    environment:
      KAFKA_LISTENERS: "INTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://event-store:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
        - zoo
  zoo:
    image: 'zookeeper:3.5'
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
